### ISSUE TITLE
bindgen generates wrong bindings for typdef-function pointers

### ISSUE THREAD

**Issue by nwin** [crabtw/rust-bindgen#212]
The following header file (which basically declares the same function signature 4 times)
```c
typedef void (*FnPtr)();
typedef void Fn();
void function1(FnPtr proc);
void function2(Fn *proc);
void function3(Fn proc);
void function4(void (*proc)());
```
results in the following rust code:
```rust
pub type FnPtr = ::std::option::Option<extern "C" fn() -> ()>;
pub type Fn = ::libc::c_void;
extern "C" {
    pub fn function1(_proc: FnPtr) -> ();
    pub fn function2(_proc: *mut ::std::option::Option<extern "C" fn() -> ()>)
     -> ();
    pub fn function3(_proc: Fn) -> ();
    pub fn function4(_proc: ::std::option::Option<extern "C" fn() -> ()>)
     -> ();
}
```

The generated code for `function1` and `function4` is correct. `function2` is declared as taking a pointer to a function pointer. `function3` is declared as taking void because `Fn` is incorrectly assumed to be a `::libc::c_void` in this case.

So there are two errors:
 1. A function typedef without star and arguments is parsed wrongly as `::libc::c_void`
 2. If the star is in the function signature, it correctly parsed as a function, but another pointer indirection is added.

**Comment by jethrogb** [comment]
I just encountered this issue today.

**Comment by jethrogb** [comment]
"error 1." does not apply when using an explicitly empty argument list (i.e. `(void)`). In that case, you get:
```rust
pub type Fn = extern "C" fn() -> ();
...
    pub fn function3(_proc: Fn) -> ();
```
Which is a non-nullable version of function1/function4. C would allow passing a NULL pointer in this case though.

**Comment by Yamakaky** [comment]
if I add an argument to Fn, it generates the expected code.

**Comment by Yamakaky** [comment]
I fixed the Fn part. It was because the type of Fn was http://clang.llvm.org/doxygen/classclang_1_1FunctionNoProtoType.html

**Comment by Yamakaky** [comment]
Solved

**Comment by jethrogb** [comment]
This bug is not fixed, please re-open. It seems only the `(void)` parameter list has been fixed.

With the latest git:
```c
typedef void (*FnPtr)();
typedef void Fn();
void function1(FnPtr proc);
void function2(Fn *proc);
void function3(Fn proc);
void function4(void (*proc)());
```
Results in:
```rust
pub type FnPtr = ::std::option::Option<extern "C" fn()>;
pub type Fn = extern "C" fn();
extern "C" {
    pub fn function1(proc_: FnPtr);
    pub fn function2(proc_: *mut Fn);
    pub fn function3(proc_: Fn);
    pub fn function4(proc_: ::std::option::Option<extern "C" fn()>);
}
```
As OP says, these should all have **exactly the same** signature. So, the following issues remain:
1. There should be no difference between `Fn` and `FnPtr`, they should both be a nullable function pointer (`Option<fn()>`)
2. `function2` should not include `*mut`

**Comment by Yamakaky** [comment]
I think the current code is correct. However, it may be acceptable that `Fn` == `FnPtr`, especially for the `NULL` part. Would you mind to PR?

**Comment by jethrogb** [comment]
> I think the current code is correct.

It's not. In C, the first level in direction in a function pointer is ignored:

```C
// with -Werror -Wall
typedef void Fn();
void function1(Fn proc);
void function2(Fn* proc);
void function3(Fn** proc);
void function4(Fn proc);

void function1(Fn proc) {
	function2(proc); // Ok
}

void function2(Fn* proc) {
	function1(proc); // Ok
}

void function3(Fn** proc) {
	function1(proc); // error: incompatible pointer types passing 'Fn **' (aka 'void (**)()') to parameter of type 'Fn *' (aka 'void (*)()')
	// also note the type in the error message added a *
}

// You can even mix */no * in declaration and definition
void function4(Fn* proc) { // Ok
	function1(proc);
}
```

> Would you mind to PR?

Sorry I don't have time to look into this right now.
